services:
  app.fresh-project:
    container_name: fresh-project
    image: denoland/deno:latest
    ports:
      - "9001:5173"
    volumes:
      - "C:\\Users\\mlugo\\SideProjects\\fresh-project:/app"
      - deno-node-modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "deno install --allow-scripts && deno task dev"

volumes:
  deno-node-modules:
